### ISSUE TITLE
Unable to build: "No rule to make target 'dist/install'.  Stop."

### ISSUE THREAD

**Issue by HunterGraubard** [johannesjh/fava-gtk#4]
I'm attempting to build the Flatpak package as per the instructions. I'm running Fedora Silverblue and am trying to build this in a toolbox. I cloned the repository and entered its directory. I then ran:

```
make -C packaging/flatpak dist/install
```

This gives the following output:

```
make: Entering directory '/var/mnt/Temp/fava-gtk/packaging/flatpak'
make: *** No rule to make target 'dist/install'.  Stop.
make: Leaving directory '/var/mnt/Temp/fava-gtk/packaging/flatpak'
```

What's happening here?

PS: It'd be great if you could get this up on Flathub!

**Comment by johannesjh** [comment]
hi, sorry the instructions in the README were false; I updated the makefile in commit ce196f4e275d7004ac3930fdf1f7d9e2169ed325. The command `make -C packaging/flatpak install` should work fine. I currently don't have my development laptop available so I could not verify it again. But if you look at the [Makefile](https://github.com/johannesjh/fava-gtk/blob/main/packaging/flatpak/Makefile) you will quickly see what targets are available.

I won't upload to flathub just yet because the project is very young and still rather immature (as you have had to experience first hand). This means I am starting rather slowly, hoping to first gather personal experience as well as feedback from the dev community. I also would like to add some unit tests and automate the build process. Then I can upload ci-builds from a master or release branch to flathub.

**Comment by HunterGraubard** [comment]
Hmm. Thanks for your help, but I'm still having trouble. With that new command, I get the following output:

```
make: Entering directory '/var/mnt/Temp/fava-gtk/packaging/flatpak'
flatpak --user uninstall -y io.github.beancount.FavaGtk
error: io.github.beancount.FavaGtk/*unspecified*/*unspecified* not installed
make: [Makefile:25: uninstall] Error 1 (ignored)
desktop-file-validate io.github.beancount.FavaGtk.desktop
appstreamcli validate io.github.beancount.FavaGtk.appdata.xml
make: appstreamcli: No such file or directory
make: *** [Makefile:13: dist/io.github.beancount.FavaGtk.flatpak] Error 127
make: Leaving directory '/var/mnt/Temp/fava-gtk/packaging/flatpak'
```

I don't exactly know what I'm doing, but `appstreamcli` doesn't seem to exist on my system, but I do have an `appstream-util`. So I changed the Makefile to run `appstream-util validate` instead, and now I get this output:

```
make: Entering directory '/var/mnt/Temp/fava-gtk/packaging/flatpak'
flatpak --user uninstall -y io.github.beancount.FavaGtk
error: io.github.beancount.FavaGtk/*unspecified*/*unspecified* not installed
make: [Makefile:25: uninstall] Error 1 (ignored)
desktop-file-validate io.github.beancount.FavaGtk.desktop
appstream-util validate io.github.beancount.FavaGtk.appdata.xml
io.github.beancount.FavaGtk.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• style-invalid         : Not enough <screenshot> tags, minimum is 1
• tag-missing           : <release> required
• tag-missing           : <url> is not present
Validation of files failed
make: *** [Makefile:13: dist/io.github.beancount.FavaGtk.flatpak] Error 1
make: Leaving directory '/var/mnt/Temp/fava-gtk/packaging/flatpak'
```

Thanks again.

**Comment by johannesjh** [comment]
To make it easier for you to get started, I have released an initial version [v0.1.0](https://github.com/johannesjh/fava-gtk/releases/tag/v0.1.0) and uploaded a locally built flatpak bundle.

Regarding `appstreamcli validate`: Have you tried installing appstreamcli? It is provided in [fedora's appstream package](https://pkgs.org/download/appstream). I do not have the impression that appstreamcli and appstream-util can be used interchangeably. It appears that `appstream-util validate` performs many additional checks, and that [most flatpak packages do not pass appstreamutil's validations](https://github.com/AppImage/AppImageKit/issues/603). I think you should first try to get the build working using the `appstreamcli validate` command, and only later add additional validations if you wish to do so.

Would you be willing to document the system requirements needed to get the build working? A pull request with an improved README would be very welcome :-). E.g., like this, off the top of my head:

```markdown
System requirements for running the fava-gtk flatpak bundle

* Flatpak (Note: flatpak will automatically install the GNOME runtime when installing fava-gtk)


Additional system requirements for running fava-gtk's python code (i.e., without flatpak):

* git
* Python >= 3.8
* PyGObject >= 3.36 (installed as system package or using pip, see https://pygobject.readthedocs.io/en/latest/getting_started.html)
* The Python GI Repository must contain bindings to webkit2 API level 4 (e.g., https://packages.debian.org/jessie/gir1.2-webkit2-4.0)
* pre-commit (checks code prior to committing changes)
* virtualenv (to avoid messing with python's system-wide site packages)
* python poetry (currently used to install all other python dependencies and to build fava-gtk, might change in the future see https://github.com/johannesjh/fava-gtk/issues/2)


Additional system requirements for building flatpak bundles:

* flatpak-builder (installed using instructions from https://docs.flatpak.org/en/latest/first-build.html, the GNOME SDK will also be installed as part of the build process)
* appstream (provides the appstreamcli command)
* desktop-file-utils (provides the desktop-file-validate command)
```

**Comment by johannesjh** [comment]
I went ahead and documented system requirements based on the notes above, see modified README. (Notes: I did this while refactoring the dependency management in order to fix https://github.com/johannesjh/fava-gtk/issues/2, this means that the build process has changed a bit). I will close this issue if you don't mind.... the system requirements are now documented, the build is working fine as far as I know, and I have provided a flatpak package in case you dont' want to build yourself. You can let me know if you experience further problems.

**Comment by HunterGraubard** [comment]
Sorry for the late response. Thanks for your help. Sadly I'm still not really able to get it working on my end due to the distribution I'm running. On Fedora Silverblue, it's not really intended or encouraged to install loads of development stuff directly on to the system, so I don't want to install things like `appstream` or all the Python requirements or whatever else. On Fedora Silverblue, such tasks are supposed to be run inside a Fedora Toolbox. Normally I can do that with no problems, but in this case I just can't figure it out. I don't seem to be able to install `flatpak` in the Toolbox, and so I can't build the Flatpak in an environment where I also have `appstream` and everything else simultaneously.

The package you uploaded works fine though so I'll just have to use that, and give up on building it myself. Thanks anyway!

**Comment by johannesjh** [comment]
Silverblue looks interesting. From what I read, I think you can install stuff using `dnf`, this will create an overlay over the ostree file system tree. But yes, this does not seem to be the normal way how you are supposed to install stuff. Instead, developers seem to use [toolbox](https://docs.fedoraproject.org/en-US/fedora-silverblue/toolbox/) to set up dev environments in containers. You could then install all the tools you need inside your toolbox.

Another idea: the validations could be run as part of the flatpak build, and thus inside the flatpak sandbox. Unfortunately, the `appstreamcli` binary is not available within a flatpak build step, and I do not know how additional packages (like compilers, validators etc) can be installed in flatpak builder modules.

**Comment by johannesjh** [comment]
I renamed this issue to better reflect what it is currenctly about.  
Old issue name: Unable to build: "No rule to make target 'dist/install'.  Stop."  
New issue name: Check if the appstream and desktop files can be validated within a flatpak build sandbox (instead of on the host)

**Comment by johannesjh** [comment]
I played around with different options but I do not have a nice solution.

* I tried moving the appstream validation into the flatpak build. But the appstream build images do not come with a package manager (except for pip and maybe others that I did not find?), which makes it difficult to install the appstream package and run its validate command during the flatpak build.
* We could switch to the stricter validation provided by `appstream-util validate`. This would probably improve the package metadata, but I am not very keen on implementing this. 
* We could remove the validation altogether (or make it optional).

Are you interested in working on this issue? It is not so important to me... so if you don't mind, I would close this ticket.

**Comment by johannesjh** [comment]
closing this issue
